services:
  - type: web
    name: emotion-detection-websocket
    env: python
    runtime: python
    region: oregon
    plan: free
    rootDir: ml_server
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python emotion_dashboard.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
